# pre ops
- import_playbook: playbooks/operational/pre_ops.yml
  tags: ["pre_ops"]

# main ops
- import_playbook: playbooks/operational/main.yml
  tags: ["main"]
  
# post ops
- import_playbook: playbooks/operational/post_ops.yml
  tags: ["post_opts"]

