- hosts: 
    - masters
    - workers
  gather_facts: true
  become: True
  any_errors_fatal: false
  tags: ['k3s']
  tasks:
    - import_role:
        name: k3s
        tasks_from: download
      tags: ['download_k3s']
