- hosts: 
    - masters
    - workers
  gather_facts: true
  become: True
  any_errors_fatal: false
  tags: ['download_k3s']
  tasks:
    - import_role:
        name: k3s
        tasks_from: download
      tags: ['download_k3s']

- hosts: 
    - masters
  gather_facts: true
  become: True
  any_errors_fatal: false
  tags: ['install_master']
  tasks:
    - import_role:
        name: k3s
        tasks_from: setup_master
      tags: ['install_master']

- hosts: 
    - workers
  gather_facts: true
  become: True
  any_errors_fatal: false
  tags: ['install_worker']
  tasks:
    - import_role:
        name: k3s
        tasks_from: setup_worker
      tags: ['install_worker']
