- hosts: 
    - masters
    - workers
  gather_facts: true
  become: True
  any_errors_fatal: false
  tags: ['download_k3s']
  tasks:
    - import_role:
        name: k3s
        tasks_from: download
      tags: ['download_k3s']

- hosts: 
    - masters
    - workers
  gather_facts: true
  become: True
  any_errors_fatal: false
  tags: ['k3s_uninstall']
  tasks:
    - import_role:
        name: k3s
        tasks_from: k3s_uninstall
      tags: ['k3s_uninstall']

- hosts: 
    - masters
  gather_facts: true
  become: True
  any_errors_fatal: false
  tags: ['install_master']
  tasks:
    - import_role:
        name: k3s
        tasks_from: k3s_uninstall
      tags: ['k3s_uninstall']
    - import_role:
        name: k3s
        tasks_from: download
      tags: ['download_k3s']
    - import_role:
        name: k3s
        tasks_from: setup_master
      tags: ['install_master']
    - import_role:
        name: k3s
        tasks_from: get_tokens
      tags: ['get_tokens']

- hosts: 
    - workers
  gather_facts: true
  become: True
  any_errors_fatal: false
  tags: ['install_worker']
  tasks:
    - import_role:
        name: k3s
        tasks_from: k3s_uninstall
      tags: ['k3s_uninstall']
    - import_role:
        name: k3s
        tasks_from: download
      tags: ['download_k3s']
    - import_role:
        name: k3s
        tasks_from: setup_worker
      tags: ['install_worker']
