- hosts:
    - masters
    - workers
  gather_facts: True
  become: True
  any_errors_fatal: false
  tags: ['pre_ops']
  tasks:
    - import_role:
        name: common
        tasks_from: upgrade
      tags: ["pre_ops"]
    - import_role:
        name: common
        tasks_from: install_zerotier

