- name: Copy K3s service file for the workers
  register: k3s_service
  template:
    src: "k3s-worker.service.j2"
    dest: "k3s.service"
    owner: root
    group: root
    mode: 0755
  when: ( "{{ inventory_hostname }}" != "{{ groups['masters'][0] }}" )

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes
  retries: 5
  delay: 5
  register: result
  until: result is not failed
  when: ( "{{ inventory_hostname }}" != "{{ groups['masters'][0] }}" )

- name: Wait for node-token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Register node-token file access mode
  stat:
    path: /var/lib/rancher/k3s/server
  register: p

- name: Change file access node-token
  file:
    path: /var/lib/rancher/k3s/server
    mode: "g+rx,o+rx"

- name: Read node-token from masters
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Store masters node-token
  set_fact: 
   token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- name: Restore node-token file access 
  file:
    path: /var/lib/rancher/k3s/server
    mode: "{{ p.stat.mode }}"

- name: Create directory .kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"

- name: Copy config file to user home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"

# Check this part
- name: Replace https://localhost:6443 by https://masters-pi:6443
  command: k3s kubectl config set-cluster default
    --server=https://{{ masters_ip }}:6443
    --kubeconfig ~{{ ansible_user }}/.kube/config

- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link