k3s_version: v1.23.4+k3s1
system_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
master_ip: "{{ hostvars[groups['masters'][0]]['ansible_host'] | default(groups['masters'][0]) }}"
