# run zerotier command with ansible to join network
# zerotier-cli join <network_id>
#- name: zerotier join network
#  shell: zerotier-cli join {{ zerotier_network_id }}
#  when: zerotier_network_id is defined

- name: zerotier | join network
  command: zerotier-cli -j join {{ zerotier_network_id }}
  register: zerotier_network
  when: not ansible_check_mode
  changed_when: false
  tags:
    - zerotier

# create directory with ansible
- name: create ansible directory
  file:
    path: /usr/local/etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0775
    #group: root

- name: zerotier | add ansible status collector
  copy:
    content: |
      #!/bin/sh
      zerotier-cli -j info \
      | jq .
    dest: /usr/local/etc/ansible/facts.d/zt_info.fact
    mode: 0750
    owner: root
    group: root
  tags:
    - zerotier



- name: zerotier | add ansible peer status collector
  copy:
    content: |
      #!/bin/sh
      zerotier-cli -j listpeers \
      | jq .
    dest: /usr/local/etc/ansible/facts.d/zt_peers.fact
    mode: 0750
    owner: root
    group: root
  tags:
    - zerotier

- name: zerotier | add ansible networks status collector
  copy:
    content: |
      #!/bin/sh
      zerotier-cli -j listpeers \
      | jq .
    dest: /usr/local/etc/ansible/facts.d/zt_networks.fact
    mode: 0750
    owner: root
    group: root
  tags:
    - zerotier

- name: zerotier | get local node address
  # check_mode: no means "always run this task"
  command: zerotier-cli -j info
  register: zerotier_info
  check_mode: False
  changed_when: false
  tags:
    - zerotier

- name: zerotier | dump info response
  debug:
    var:  zerotier_info.stdout
    verbosity: 2
 # when: not ansible_check_mode
  tags:
    - zerotier

- name: zerotier | dump network response
  debug:
    var:  zerotier_network.stdout
    verbosity: 2
 # when: not ansible_check_mode
  tags:
    - zerotier

- name: zerotier | register responses
  set_fact:
    zerotier_address: "{{ (zerotier_info.stdout |from_json).address }}"
    zerotier_device:  "{{ (zerotier_network.stdout |from_json).portDeviceName }}"
    zerotier_name:    "{{ (zerotier_network.stdout |from_json).name }}"
    zerotier_ip:      "{{ (zerotier_network.stdout |from_json).assignedAddresses }}"
    zerotier_status:  "{{ (zerotier_network.stdout |from_json).status }}"
  #when: not ansible_check_mode
  tags:
    - zerotier

